config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

# Defines the root path route ("/")
# Root route
root "cars#index"

# Car resources
resources :cars do
  resources :reviews
  resources :favourites, only: [ :create, :destroy ]
  collection do
    get "models"
  end
end

# Battles resources
resources :battles, only: [ :index, :create ] do
  collection do
    get "new_cars", to: "battles#new_cars"
    get "leaderboard", to: "battles#leaderboard"
    post "vote/:id", to: "battles#vote", as: "vote_battle"
  end
end

# Aliased routes
get "car_battle", to: "battle#index", as: "car_battle"
get "battles/new_cars", to: "battle#new_cars"

# Favourites resources
resources :favourites, only: [ :index ]

# Pick a car
get "pick_a_car", to: "cars#pick"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favourites
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :comment, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than: 0, less_than: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def new_cars
    car1 = Car.order("RANDOM()").first
    car2 = Car.order("RANDOM()").where.not(id: car1.id).first
    render json: {
      car1: {
        id: car1.id,
        brand: car1.brand,
        model: car1.model,
        year: car1.year,
        fuel: car1.fuel,
        image_url: car1.image_url,
        votes_count: car1.votes_count
      },
      car2: {
        id: car2.id,
        brand: car2.brand,
        model: car2.model,
        year: car2.year,
        fuel: car2.fuel,
        image_url: car2.image_url,
        votes_count: car2.votes_count
      }
    }
  end
  def index
    @car1, @car2 = Car.order("RANDOM()").limit(2)
    @top_cars = Car.where("votes_count > ?", 0).order(votes_count: :desc).limit(3)
  end

  def create
    car = Car.find(params[:car_id])
    car.increment!(:votes_count)
    render json: { success: true }
  end
  def vote
    @car = Car.find(params[:id]) # This is the car that was voted for
    @car.increment!(:votes_count) # Increment the vote count

    @votes_count = @car.votes_count # Get the updated vote count

    # Load new cars for the next round
    @car1 = Car.order("RANDOM()").first
    @car2 = Car.order("RANDOM()").where.not(id: @car1.id).first

    respond_to do |format|
      format.js
      format.json { render json: { success: true, votes_count: @votes_count, car1: @car1, car2: @car2 } }
    end
  end

  def leaderboard
    @top_cars = Car.where("votes_count > ?", 0).order(votes_count: :desc).limit(3)
    render partial: "battles/leaderboard", locals: { top_cars: @top_cars }
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all

    # Filtering based on parameters
    if params[:brand].present?
      @cars = @cars.where(brand: params[:brand])
    end

    if params[:fuel].present?
      @cars = @cars.where(fuel: params[:fuel])
    end

    if params[:year].present?
      @cars = @cars.where(year: params[:year])
    end
  end

  def show
    @car = Car.find(params[:id])
    @reviews = @car.reviews
    @review = Review.new
    @favourites = Favourite.where(car: @car)
  end

  def pick
    @car = Car.order("RANDOM()").first

    respond_to do |format|
      format.html # for regular requests
      format.js   # for AJAX requests
    end
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :find_car, only: [ :create, :destroy ]

  def create
    Rails.logger.debug("Parameters: #{params.inspect}")

    @favourite = Favourite.new(car: @car)

    if @favourite.save
      respond_to do |format|
        format.js # Keep this if you want to show alerts on the index page via AJAX
        format.html { redirect_to @car, notice: "Favourite was successfully added." }
      end
    else
      respond_to do |format|
        format.html { redirect_to @car, alert: "Could not add to favourites." }
        format.js { render js: "alert('Error: Could not add to favourites');" }
      end
    end
  end


  def destroy
    Rails.logger.debug("Parameters: #{params.inspect}")

    @favourite = Favourite.find(params[:id])
    @car = @favourite.car
    @favourite.destroy

    respond_to do |format|
      format.html { redirect_to @car, notice: "Favourite was successfully removed." }
      format.js
    end
  end


  def index
    @favourites = Favourite.all
  end

  private

  def find_car
    @car = Car.find(params[:car_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_car

  def create
    @review = @car.reviews.new(review_params)

    if @review.save
      Rails.logger.debug "Review saved successfully."
      respond_to do |format|
        format.js
      end
    else
      Rails.logger.debug "Review failed to save: #{@review.errors.full_messages.join(', ')}"
      respond_to do |format|
        format.js { render js: "alert('Failed to save review: #{@review.errors.full_messages.join(', ')}');" }
      end
    end
  end


  def destroy
    @review = Review.find(params[:id]) # Ensure you find the review by ID
    @review.destroy

    respond_to do |format|
      format.html { redirect_to car_path(@review.car), notice: "Review was successfully deleted." }
      format.js   # This will render destroy.js.erb
    end
  rescue ActiveRecord::RecordNotFound
    respond_to do |format|
      format.html { redirect_to car_path(@review.car), alert: "Review not found." }
      format.js   # You might want to handle the error on the client side
    end
  end


  private

  def set_car
    @car = Car.find(params[:car_id])
  end

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/battles/index.html.erb
<div class="container mx-auto p-6">
  <h1 class="text-5xl font-bold mb-6 mt-4 text-center">Make your pick!</h1>
  
  <div class="battle-container grid grid-cols-1 md:grid-cols-7 gap-4 items-center text-center" id="car-container">

    <div class="card bg-white p-6 rounded-lg shadow-md col-span-7 md:col-span-3 mx-2 text-center">
      <h2 class="text-2xl font-semibold"><%= @car1.brand %> <%= @car1.model %></h2>
      <img src="<%= @car1.image_url %>" alt="<%= @car1.brand %> <%= @car1.model %>" class="w-full object-cover rounded-lg mb-4" id="battle-car-img">
      <p class="text-lg text-gray-600 mb-2"><strong>Year:</strong> <%= @car1.year %></p>
      <p class="text-lg text-gray-600 mb-2"><strong>Fuel:</strong> <%= @car1.fuel %></p>
      
      <p class="text-lg text-gray-600 mb-2">
        <strong>Votes:</strong> 
        <span id="vote-count-<%= @car1.id %>"><%= @car1.votes_count || 0 %></span>
      </p>
      
      <%= button_to "Vote for This Car", vote_battle_battles_path(@car1.id), method: :post, remote: true, class: "vote-btn bg-green-500 text-white py-2 px-6 rounded-lg hover:bg-green-600 transition-all mt-4", data: { car_id: @car1.id } %>
    </div>

    <div class="vs-text text-3xl font-bold mx-auto col-span-7 md:col-span-1 md:py-6">VS</div>

    <div class="card bg-white p-6 rounded-lg shadow-md col-span-7 md:col-span-3 mx-2 text-center">
      <h2 class="text-2xl font-semibold"><%= @car2.brand %> <%= @car2.model %></h2>
      <img src="<%= @car2.image_url %>" alt="<%= @car2.brand %> <%= @car2.model %>" class="w-full object-cover rounded-lg mb-4" id="battle-car-img">
      <p class="text-lg text-gray-600 mb-2"><strong>Year:</strong> <%= @car2.year %></p>
      <p class="text-lg text-gray-600 mb-2"><strong>Fuel:</strong> <%= @car2.fuel %></p>
      
      <p class="text-lg text-gray-600 mb-2">
        <strong>Votes:</strong> 
        <span id="vote-count-<%= @car2.id %>"><%= @car2.votes_count || 0 %></span>
      </p>
      <%= button_to "Vote for This Car", vote_battle_battles_path(@car2.id), method: :post, remote: true, class: "vote-btn bg-green-500 text-white py-2 px-6 rounded-lg hover:bg-green-600 transition-all mt-4", data: { car_id: @car2.id } %>
    </div>
  
  </div>

  <h2 class="text-3xl font-bold mt-10 mb-6 text-center">Leaderboard</h2>
  <div id="leaderboard">
    <%= render partial: 'battles/leaderboard', locals: { top_cars: @top_cars } %>
  </div>
</div>

app/views/battles/vote.js.erb
// Update the vote count for the car

Swal.fire({
  title: 'Vote Recorded!',
  text: "You've voted for <%= @car.brand %> <%= @car.model %>.",
  icon: 'success',
  confirmButtonText: 'Cool!',
});

if (typeof voteCountElement == 'undefined') {
let voteCountElement = document.querySelector(`#vote-count-<%= @car.id %>`);
if (voteCountElement) {
  voteCountElement.innerText = <%= @votes_count %>; // Update with the new count
}
else {
  voteCountElement.innerText = <%= @votes_count %>; // Update with the new count
}
}
// After a delay, load new cars
setTimeout(() => {
  loadNewCars();
    updateLeaderboard();
}, );


function loadNewCars() {
  fetch('/battles/new_cars')  // This route should return two new cars
    .then(response => {
      if (!response.ok) {
        throw new Error("Network response was not ok");
      }
      return response.json();
    })
    .then(data => {
      // Assuming data contains car1 and car2 information
      const carContainer = document.querySelector('#car-container');
      
      const car1HTML = `
     <div class="card bg-white p-6 rounded-lg shadow-md col-span-7 md:col-span-3 mx-2 text-center">
      <h2 class="text-2xl font-semibold"><%= @car1.brand %> <%= @car1.model %></h2>
      <img src="<%= @car1.image_url %>" alt="<%= @car1.brand %> <%= @car1.model %>" class="w-full object-cover rounded-lg mb-4" id="battle-car-img">
      <p class="text-lg text-gray-600 mb-2"><strong>Year:</strong> <%= @car1.year %></p>
      <p class="text-lg text-gray-600 mb-2"><strong>Fuel:</strong> <%= @car1.fuel %></p>
      
      <p class="text-lg text-gray-600 mb-2">
        <strong>Votes:</strong> 
        <span id="vote-count-<%= @car1.id %>"><%= @car1.votes_count || 0 %></span>
      </p>
      
      <%= button_to "Vote for This Car", vote_battle_battles_path(@car1.id), method: :post, remote: true, class: "vote-btn bg-green-500 text-white py-2 px-6 rounded-lg hover:bg-green-600 transition-all mt-4", data: { car_id: @car1.id } %>
    </div>
      `;
      
      const car2HTML = `
       <div class="card bg-white p-6 rounded-lg shadow-md col-span-7 md:col-span-3 mx-2 text-center">
      <h2 class="text-2xl font-semibold"><%= @car2.brand %> <%= @car2.model %></h2>
      <img src="<%= @car2.image_url %>" alt="<%= @car2.brand %> <%= @car2.model %>" class="w-full object-cover rounded-lg mb-4" id="battle-car-img">
      <p class="text-lg text-gray-600 mb-2"><strong>Year:</strong> <%= @car2.year %></p>
      <p class="text-lg text-gray-600 mb-2"><strong>Fuel:</strong> <%= @car2.fuel %></p>
      
      <p class="text-lg text-gray-600 mb-2">
        <strong>Votes:</strong> 
        <span id="vote-count-<%= @car2.id %>"><%= @car2.votes_count || 0 %></span>
      </p>
      
      <%= button_to "Vote for This Car", vote_battle_battles_path(@car2.id), method: :post, remote: true, class: "vote-btn bg-green-500 text-white py-2 px-6 rounded-lg hover:bg-green-600 transition-all mt-4", data: { car_id: @car2.id } %>
    </div>
      `;
      
      carContainer.innerHTML = `${car1HTML}<div class="vs-text text-3xl font-bold mx-auto col-span-7 md:col-span-1 md:py-6">VS</div>${car2HTML}`;
    })
    .catch(error => {
      console.error('There was a problem with the fetch operation:', error);
    });
}

function updateLeaderboard() {
  fetch('<%= leaderboard_battles_path %>', {
    headers: {
      'X-Requested-With': 'XMLHttpRequest'
    }
  })
  .then(response => response.text())
  .then(html => {
    document.querySelector('#leaderboard').innerHTML = html; // Update leaderboard section
  });
}

app/views/cars/model.html.erb
<h1 class="text-2xl font-bold mb-4">Models for <%= @models.first['Make_Name'] %></h1>

<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
  <% @models.each do |model| %>
    <div class="border p-4 rounded-lg shadow-md hover:shadow-lg transition">
      <h2 class="text-xl font-semibold"><%= model['Model_Name'] %></h2>
      <p>Year: <%= model['Model_Year'] %></p>
      <%= link_to 'View Details', car_path(model['Model_ID']), class: 'text-blue-500 hover:underline' %>
    </div>
  <% end %>
</div>

<%= link_to 'Back to Makes', cars_path, class: 'mt-4 inline-block text-blue-500 hover:underline' %>

app/views/cars/pick.html.erb
<div class="container mx-auto p-6">
  <div class="max-w-5xl mx-auto mt-4">
    <div class="card bg-white shadow rounded-lg p-4 transition-transform transform hover:scale-105 hover:shadow-xl hover:bg-gray-100 mx-auto" style="max-width: 1000px; height: 600px;">
      <a href="/cars/<%= @car.id %>" style="display: block; height: 530px;">
        <h1 class="text-xl text-center font-semibold pb-2"><%= @car.brand %> <%= @car.model %></h1> 
        <img src="<%= @car.image_url %>" alt="<%= @car.brand %> <%= @car.model %>" class="w-full h-full object-cover rounded-lg mb-2">
      </a>
    </div>

<div class="ajax-favourites-form-pick mt-4 w-full"> 
<%= link_to 'Pick Another Car', pick_a_car_path, remote: true, class: 'w-full bg-blue-500 text-white p-2 rounded block hover:bg-blue-600 text-center' %>

</div>

  </div>
</div>

app/views/cars/pick.js.erb
// Update the car information without refreshing the page
console.log("Picked new car");
document.querySelector('.card').innerHTML = `
<a href="/cars/<%= @car.id %>" style="display: block; height: 530px;">
        <h1 class="text-xl text-center font-semibold pb-2"><%= @car.brand %> <%= @car.model %></h1> 
        <img src="<%= @car.image_url %>" alt="<%= @car.brand %> <%= @car.model %>" class="w-full h-full object-cover rounded-lg mb-2">
      </a>
`;

app/views/cars/show.html.erb
<div class="container-show mx-auto p-6">
  <div class="bg-white p-6 rounded-lg shadow-md mb-6">
    <h1 class="text-4xl font-bold mb-4">
      <%= @car.brand %> <%= @car.model %> (Year: <%= @car.year %>)
    </h1>
    
    <%= image_tag @car.image_url, alt: "#{@car.brand} #{@car.model}", class: "w-full h-64 object-cover rounded-lg mb-4 cursor-pointer show-car" %>

    <h2 class="text-2xl font-semibold mt-4">Current owner:</h2>
    <p class="text-2xl text-blue-900 mb-2"><%= @car.owner.nickname %></p>
    <p class="text-lg text-gray-700 mb-2"><strong class="text-black">Fuel type: </strong><%= @car.fuel %></p>
    <p class="text-lg text-gray-600 mb-2" style="border-bottom: black solid; padding-bottom: 15px">
      <strong class="text-black">VIN:</strong> <%= @car.vin %>
    </p>

    <h3 class="text-xl font-semibold mt-4">Favourites:</h3>
    <p class="text-lg text-gray-600 mb-4">
      <span id="favourites-count"><%= @favourites.count %></span> people have favourited this car.
    </p>

    <div class="ajax-favourites-form">
      <% if @favourites.any? { |f| f.car_id == @car.id } %>
        <%= form_with url: car_favourite_path(@car, @favourites.find { |f| f.car_id == @car.id }), method: :delete, local: false, data: { remote: true, turbo: false }, class: "favourites-form" do %>
          <%= submit_tag "Remove from Favourites", class: 'mt-2 bg-red-500 text-white p-2 rounded hover:bg-red-600 cursor-pointer' %>
        <% end %>
      <% else %>
        <%= form_with(url: car_favourites_path(@car), method: :post, local: false) do |form| %>
          <%= form.submit "Add to Favourites", class: "mt-2 bg-green-500 text-white p-2 rounded hover:bg-green-600 cursor-pointer" %>
        <% end %>
      <% end %>
    </div>
  </div>
  <!-- Add a flex container for the buttons -->
 

<h3 class="text-xl font-semibold mt-6">Reviews:</h3>

<% if @car.reviews.any? %> 
  <ul class="reviews-list space-y-4 mt-4">
    <% @car.reviews.each do |review| %>
      <li id="review_<%= review.id %>" class="bg-white shadow-md rounded-lg p-4 border-l-4 border-black">
        <div class="flex justify-between items-center">
          <div class="flex items-center space-x-2">
            <span class="text-yellow-400">
              <% review.rating.times do %>
                <i class="fa fa-star"></i>
              <% end %>
              <% (5 - review.rating).times do %>
                <i class="fa fa-star-o"></i> 
              <% end %>
            </span>
            <p class="text-gray-800 font-semibold">
              <%= review.comment %>
            </p>
          </div>
          <button class="delete-review bg-red-500 text-white py-2 px-4 rounded-full hover:bg-red-600 transition-all"
                  data-review-id="<%= review.id %>" 
                  data-review-url="<%= car_review_path(@car, review) %>">
            <i class="fa fa-trash-o"></i> 
          </button>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="text-lg text-gray-600 mt-4 p-4 bg-gray-100 rounded-lg">
    There are no reviews for this car yet. Be the first to leave one!
  </p>
<% end %>



  <h3 class="text-xl font-semibold mt-6">Leave a Review</h3>
  <%= render 'review_form', car: @car, review: @review %>

  <% if flash[:notice] %>
    <div id="flash-alert" class="bg-green-500 text-white p-4 rounded fixed top-4 right-4 z-50">
      <%= flash[:notice] %>
    </div>
  <% end %>
</div>

app/views/favourites/create.js.erb
// create.js.erb
Swal.fire({
  title: 'Added to Favorites',
  text: 'You have added <%= @car.brand %> <%= @car.model %> to your favourites, great choice!',
  icon: 'success',
  confirmButtonText: 'OK',
});

console.log("Favourite added:");

// Update the favorites form to show the "Remove from Favourites" button
if (typeof formContainer == 'undefined'){
const formContainer = document.querySelector('.ajax-favourites-form');
if (formContainer) {
  formContainer.innerHTML = `
    <form action="<%= car_favourite_path(@car, @favourite) %>" method="post" data-remote="true" local="false" >
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Remove from Favourites" class="mt-2 bg-red-500 text-white p-2 rounded hover:bg-red-600 cursor-pointer">
    </form>
  `;
}
}

app/views/favourites/destroy.js.erb
if (typeof favouriteElement == 'undefined'){
const favouriteElement = document.querySelector('#favourite_<%= @favourite.id %>');
if (favouriteElement) {
  favouriteElement.remove();
}
console.log("Favourite removed:", favouriteElement);
};

Swal.fire({
  title: 'Removed from Favourites',
  text: 'Removed <%= @favourite.car.brand %> <%= @favourite.car.model %> from your favourites.',
  icon: 'warning',
  confirmButtonText: 'OK',
});


if (typeof formContainer == 'undefined'){
const formContainer = document.querySelector('.ajax-favourites-form');
  formContainer.innerHTML = ` 
    <%= form_with(url: car_favourites_path(@car), method: :post, local: false) do |form| %>
      <%= form.submit "Add to Favourites", class: "mt-2 bg-green-500 text-white p-2 rounded hover:bg-green-600 cursor-pointer" %>
    <% end %>
  `;}

if (typeof formContainerPick == 'undefined'){
const formContainerPick = document.querySelector('.ajax-favourites-form-pick');
if (formContainerPick) {
  formContainerPick.innerHTML = `
<%= form_with(url: car_favourites_path(@car), method: :post, local: false) do |form| %>
      <%= form.submit "Add to Favourites", class: "mt-2 bg-green-500 w-full text-white p-2 rounded block text-center hover:bg-green-600 cursor-pointer" %>
          <% end %>

  `;
}
}

app/views/favourites/index.html.erb
<div class="container mx-auto flex flex-col md:flex-row">
<ul class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 m-8">
  <% if @favourites.present? && @favourites.any? %>
    <% @favourites.each do |favourite| %>
      <li id="favourite_<%= favourite.id %>" class="card-fav relative bg-white shadow rounded-lg p-4  hover:shadow-xl hover:bg-gray-100">
        
        <%= button_to 'X', car_favourite_path(favourite.car, favourite), 
    method: :delete, 
    remote: true, 
    class: "absolute top-2 right-2 text-red-500 hover:text-red-700 w-14 p-2 bg-white rounded-full shadow" %>

        <%= link_to car_path(favourite.car) do %>
          <% car = favourite.car %>
          <% if car.image_url.present? %>
            <img src="<%= car.image_url %>" alt="<%= car.brand %> <%= car.model %>" class="w-full h-56 object-cover rounded-t-lg mb-2">
          <% else %>
            <img src="https://via.placeholder.com/300x200" alt="No image available" class="w-full h-56 object-cover rounded-t-lg mb-2">
          <% end %>
          <h2 class="text-xl font-semibold"><%= car.brand %> <%= car.model %></h2>
          <p class="text-gray-500">Year: <%= car.year %></p>
          <p class="text-gray-500">Fuel: <%= car.fuel %></p>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <p class="text-lg text-center text-gray-600 m-8 italic">You have no cars in your favourites yet.</p>
  <% end %>
</ul>
</div>

app/views/layouts/_header.html.erb
<header class="bg-gray-800 text-white p-4">
  <nav class="container mx-auto">
    <ul class="flex space-x-4">
      <li><%= link_to 'Cars', cars_path, class: 'hover:text-gray-400' %></li>
      <li><%= link_to 'Favourites', favourites_path, class: 'hover:text-gray-400' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Rails Awesome Garage" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Afacad+Flux:wght@100..1000&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">
  <link rel="manifest" href="/manifest.json">
  <link rel="apple-touch-icon" href="<%= asset_path('ExecutiveCar_Black_icon-icons.com_54904.ico') %>">
  <link rel="icon" type="image/x-icon" href="<%= asset_path('ExecutiveCar_Black_icon-icons.com_54904.ico') %>">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
  <link href="/assets/application.tailwind.css" rel="stylesheet">
   <%= javascript_importmap_tags %> 
 <script type="module" src="<%= asset_path 'application.js' %>"></script>

  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>

<body>
<nav class="bg-gray-800 shadow-md py-4 relative">
  <div class="container mx-auto flex justify-between items-center">
    <%= link_to image_tag('car-wash.png'), root_path, style: "margin-left: 15px; border-radius: 50%; filter: invert(1); padding-left: 10px;", class: 'logo-img' %>

    <div class="flex items-center justify-center flex-1 ml-2">
      <%= link_to 'YOUR AWESOME GARAGE', root_path, class: 'logo-text text-white sm:text-xl md:text-4xl lg:text-5xl font-black' %>
    </div>

    <ul class="flex space-x-4 mr-6">
      <li><%= link_to 'Cars', cars_path, class: 'text-white navbar-link' %></li>
      <li><%= link_to 'Pick', pick_a_car_path, class: 'text-white navbar-link' %></li> 
      <li><%= link_to 'Battle', battles_path, class: 'text-white navbar-link' %></li>
      <li><%= link_to 'Favourites', favourites_path, class: 'text-white navbar-link' %></li>
    </ul>
  </div>
</nav>




<div class="content">
  <%= yield %> 
</div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/reviews/create.js.erb
<% if @review.persisted? %>
  swal.fire({
    title: "Success!",
    text: "Your review has been added successfully.",
    icon: "success",
    confirmButtonText: "Okay",
  }).then(() => {
    // Optionally, you can reload the page or do something else after the alert
    location.reload();
  });

  // Append the new review to the list
  const reviewsList = document.querySelector('.reviews-list');
  reviewsList.insertAdjacentHTML('beforeend', `
    <li id="review_<%= @review.id %>" class="border-b pb-2 mb-2 flex justify-between items-center">
      <div>
        <strong class="font-semibold">Rating:</strong> <%= @review.rating %> - <%= @review.comment %>
      </div>
      <%= button_to 'Delete', car_review_path(@car, @review), method: :delete, remote: true, class: "delete-review ml-4 bg-red-500 text-white p-1 rounded hover:bg-red-600" %>
    </li>
  `);
<% else %>
  swal.fire({
    title: "Error!",
    text: "Failed to save review: <%= j @review.errors.full_messages.join(', ') %>",
    icon: "error",
    confirmButtonText: "Okay",
  });
<% end %>